// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/audit-logs": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Query audit log entries with filters. Requires project_id.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "List audit logs",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date (RFC3339)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (RFC3339)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by action (e.g. secret.read)",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by result (success, denied, error)",
                        "name": "result",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Page number (default 1)",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Items per page (default 50, max 100)",
                        "name": "per_page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.AuditLogListResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/audit-logs/export": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Export filtered audit log entries as a CSV file.",
                "produces": [
                    "text/csv"
                ],
                "tags": [
                    "audit"
                ],
                "summary": "Export audit logs as CSV",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Start date (RFC3339)",
                        "name": "start_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "End date (RFC3339)",
                        "name": "end_date",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by action",
                        "name": "action",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by user ID",
                        "name": "user_id",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filter by result",
                        "name": "result",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    }
                }
            }
        },
        "/auth/change-vault-key": {
            "put": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Rotate vault key: verify current auth key, store new crypto material. O(1) — no item rows touched.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Change vault key",
                "parameters": [
                    {
                        "description": "Current auth proof + new crypto material",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ChangeVaultKeyRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Wrong current Vault Key",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/me": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Returns identity, vault setup status, and vault lock state.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Get auth state",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.MeResponse"
                        }
                    }
                }
            }
        },
        "/auth/recovery/incoming-requests": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Incoming recovery requests",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api_internal_handler.IncomingRequest"
                            }
                        }
                    }
                }
            }
        },
        "/auth/recovery/kit": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Returns the recovery-wrapped DEK so the client can attempt recovery.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Get recovery kit material",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.RecoveryKitResponse"
                        }
                    },
                    "403": {
                        "description": "Recovery disabled",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "No recovery kit",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/recovery/kit/recover": {
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Client verified recovery words, unwrapped DEK, set new Vault Key. Submit new crypto material.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Recover with Recovery Kit",
                "parameters": [
                    {
                        "description": "New crypto material",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.RecoverWithKitRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/recovery/request": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Recovery request status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.RecoveryRequestStatusResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Start 72-hour waiting period for trusted contact recovery.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Initiate recovery request",
                "parameters": [
                    {
                        "description": "Ephemeral public key",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.InitiateRecoveryRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Cancel recovery request",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/recovery/request/{id}/approve": {
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Trusted contact provides DEK re-wrapped with recovering user's ephemeral key.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Approve recovery request",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recovery request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Recovery payload",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ApproveRecoveryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/recovery/request/{id}/complete": {
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Complete trusted contact recovery",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Recovery request ID",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "New crypto material",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CompleteRecoveryRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/recovery/status": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Returns which recovery methods are available for this user.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Recovery status",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.RecoveryStatusResponse"
                        }
                    }
                }
            }
        },
        "/auth/recovery/trusted-contact": {
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Wrap DEK with contact's public key and store. Requires unlocked vault.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Set trusted contact",
                "parameters": [
                    {
                        "description": "Contact email + wrapped DEK",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SetTrustedContactRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Remove trusted contact",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/setup-vault": {
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Store client-generated crypto material and link to authenticated identity.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Setup vault",
                "parameters": [
                    {
                        "description": "Crypto material from client",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SetupVaultRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SetupVaultResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/unlock": {
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Verify Auth Key hash (Vault Key proof). Returns wrapped DEK + keypair on success.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Unlock vault",
                "parameters": [
                    {
                        "description": "Auth Key hash (base64)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.UnlockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.UnlockResponse"
                        }
                    },
                    "403": {
                        "description": "Wrong Vault Key",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orgs": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "List all organizations the current user is a member of.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "List organizations",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ListOrgsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Create an organization. The creating user becomes the owner and is added as an admin member.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Create organization",
                "parameters": [
                    {
                        "description": "Organization name",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CreateOrgRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.OrgResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orgs/{orgID}": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Get a single organization by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Get organization",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.OrgResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orgs/{orgID}/members": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "List all members of an organization with their roles.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "List organization members",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ListMembersResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Add a user to an organization with a specified role.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Add organization member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "User and role",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.AddMemberRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.MemberResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/orgs/{orgID}/members/{memberID}": {
            "delete": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Remove a member from an organization.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "organizations"
                ],
                "summary": "Remove organization member",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization UUID",
                        "name": "orgID",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Member UUID",
                        "name": "memberID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    },
                    "403": {
                        "description": "Forbidden",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "List all projects in an organization.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "List projects",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "organization_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ListProjectsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Create a project with client-generated crypto material. Project Vault Key shown once at creation, never stored on server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Create project",
                "parameters": [
                    {
                        "description": "Project config + crypto material",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CreateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ProjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Get a single project by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ProjectResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sdk/projects/{projectID}/crypto": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns project salt and wrapped Project DEK. SDK uses this to derive Project KEK and unwrap DEK.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get project crypto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ProjectCryptoResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sdk/secrets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List secret metadata (name hash, version, updated_at). Never returns ciphertext.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "List secrets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ListSecretsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Store an encrypted vault item. Server stores opaque ciphertext only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Create secret",
                "parameters": [
                    {
                        "description": "Encrypted secret",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CreateSecretRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sdk/secrets/bulk": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetch multiple secrets by name hashes. Used by SDK for schema manifest loading.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Bulk fetch secrets",
                "parameters": [
                    {
                        "description": "Name hashes to fetch",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.BulkFetchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api_internal_handler.SecretResponse"
                            }
                        }
                    }
                }
            }
        },
        "/sdk/secrets/{nameHash}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a single encrypted secret by name hash.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Get secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash (base64)",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment (development/staging/production)",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update ciphertext and nonce. Version auto-incremented.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Update secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "New ciphertext",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.UpdateSecretRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove a secret from the vault.",
                "tags": [
                    "secrets"
                ],
                "summary": "Delete secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sdk/secrets/{nameHash}/rollback": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revert a secret to a previous version. The current version is archived first.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Rollback secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Target version",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.RollbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sdk/secrets/{nameHash}/versions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Show version history for a secret. Returns version numbers and timestamps.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "List secret versions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.VersionsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/secrets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List secret metadata (name hash, version, updated_at). Never returns ciphertext.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "List secrets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ListSecretsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Store an encrypted vault item. Server stores opaque ciphertext only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Create secret",
                "parameters": [
                    {
                        "description": "Encrypted secret",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CreateSecretRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/secrets/bulk": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetch multiple secrets by name hashes. Used by SDK for schema manifest loading.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Bulk fetch secrets",
                "parameters": [
                    {
                        "description": "Name hashes to fetch",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.BulkFetchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api_internal_handler.SecretResponse"
                            }
                        }
                    }
                }
            }
        },
        "/secrets/{nameHash}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a single encrypted secret by name hash.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Get secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash (base64)",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment (development/staging/production)",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update ciphertext and nonce. Version auto-incremented.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Update secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "New ciphertext",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.UpdateSecretRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove a secret from the vault.",
                "tags": [
                    "secrets"
                ],
                "summary": "Delete secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/secrets/{nameHash}/rollback": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Revert a secret to a previous version. The current version is archived first.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Rollback secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "Target version",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.RollbackRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/secrets/{nameHash}/versions": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Show version history for a secret. Returns version numbers and timestamps.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "List secret versions",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.VersionsResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tokens": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "List all tokens for a project. Never exposes token hash or plaintext.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "List service tokens",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ListTokensResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Generate a scoped service token. Plaintext shown once, SHA-256 hashed before storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Create service token",
                "parameters": [
                    {
                        "description": "Token config",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CreateTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CreateTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tokens/{tokenID}": {
            "delete": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Marks a service token as revoked. Immediate effect.",
                "tags": [
                    "tokens"
                ],
                "summary": "Revoke service token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token UUID",
                        "name": "tokenID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/public-key": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recovery"
                ],
                "summary": "Lookup user public key",
                "parameters": [
                    {
                        "type": "string",
                        "description": "User email",
                        "name": "email",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.PublicKeyResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api_internal_handler.AddMemberRequest": {
            "type": "object",
            "properties": {
                "role": {
                    "description": "admin, senior_dev, dev, contractor, ci_bot",
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.ApproveRecoveryRequest": {
            "type": "object",
            "properties": {
                "recovery_payload": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.AuditLogEntry": {
            "type": "object",
            "properties": {
                "action": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "ip": {
                    "type": "string"
                },
                "metadata": {
                    "description": "JSON string",
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "result": {
                    "type": "string"
                },
                "secret_hash": {
                    "description": "base64",
                    "type": "string"
                },
                "token_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.AuditLogListResponse": {
            "type": "object",
            "properties": {
                "entries": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_handler.AuditLogEntry"
                    }
                },
                "page": {
                    "type": "integer"
                },
                "per_page": {
                    "type": "integer"
                },
                "total": {
                    "type": "integer"
                }
            }
        },
        "api_internal_handler.BulkFetchRequest": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "name_hashes": {
                    "description": "base64-encoded HMAC hashes",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "project_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.ChangeVaultKeyRequest": {
            "type": "object",
            "properties": {
                "current_auth_key_hash": {
                    "description": "base64",
                    "type": "string"
                },
                "new_auth_key_hash": {
                    "description": "base64",
                    "type": "string"
                },
                "new_salt": {
                    "description": "base64",
                    "type": "string"
                },
                "new_vault_key_type": {
                    "description": "\"pin\" or \"passphrase\"",
                    "type": "string"
                },
                "new_wrapped_dek": {
                    "description": "base64",
                    "type": "string"
                },
                "new_wrapped_private_key": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.CompleteRecoveryRequest": {
            "type": "object",
            "properties": {
                "new_auth_key_hash": {
                    "type": "string"
                },
                "new_recovery_wrapped_dek": {
                    "type": "string"
                },
                "new_salt": {
                    "type": "string"
                },
                "new_vault_key_type": {
                    "type": "string"
                },
                "new_wrapped_dek": {
                    "type": "string"
                },
                "new_wrapped_private_key": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.CreateOrgRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.CreateProjectRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "string"
                },
                "project_salt": {
                    "description": "base64 — generated client-side",
                    "type": "string"
                },
                "wrapped_project_dek": {
                    "description": "base64 — Project DEK wrapped with Project KEK",
                    "type": "string"
                },
                "wrapped_project_vault_key": {
                    "description": "base64 — Project Vault Key wrapped with user's public key",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.CreateSecretRequest": {
            "type": "object",
            "properties": {
                "ciphertext": {
                    "description": "base64 AES-256-GCM encrypted item JSON",
                    "type": "string"
                },
                "environment": {
                    "type": "string"
                },
                "name_hash": {
                    "description": "base64 HMAC-SHA256 of secret name",
                    "type": "string"
                },
                "nonce": {
                    "description": "base64 96-bit nonce",
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.CreateTokenRequest": {
            "type": "object",
            "properties": {
                "environment": {
                    "description": "development | staging | production",
                    "type": "string"
                },
                "expires_at": {
                    "description": "optional RFC3339",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permission": {
                    "description": "read | read_write",
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.CreateTokenResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "environment": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "token": {
                    "description": "shown exactly once — never stored",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.IncomingRequest": {
            "type": "object",
            "properties": {
                "eligible_at": {
                    "type": "string"
                },
                "request_id": {
                    "type": "string"
                },
                "requested_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                },
                "user_email": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.InitiateRecoveryRequest": {
            "type": "object",
            "properties": {
                "recovery_public_key": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.ListMembersResponse": {
            "type": "object",
            "properties": {
                "members": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_handler.MemberResponse"
                    }
                }
            }
        },
        "api_internal_handler.ListOrgsResponse": {
            "type": "object",
            "properties": {
                "organizations": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_handler.OrgResponse"
                    }
                }
            }
        },
        "api_internal_handler.ListProjectsResponse": {
            "type": "object",
            "properties": {
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_handler.ProjectResponse"
                    }
                }
            }
        },
        "api_internal_handler.ListSecretsResponse": {
            "type": "object",
            "properties": {
                "secrets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_handler.SecretListItem"
                    }
                }
            }
        },
        "api_internal_handler.ListTokensResponse": {
            "type": "object",
            "properties": {
                "tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_handler.TokenListItem"
                    }
                }
            }
        },
        "api_internal_handler.MeResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "salt": {
                    "description": "base64",
                    "type": "string"
                },
                "vault_key_type": {
                    "type": "string"
                },
                "vault_setup_complete": {
                    "type": "boolean"
                },
                "vault_unlocked": {
                    "type": "boolean"
                }
            }
        },
        "api_internal_handler.MemberResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "joined_at": {
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.OrgResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.ProjectCryptoResponse": {
            "type": "object",
            "properties": {
                "project_salt": {
                    "description": "base64",
                    "type": "string"
                },
                "wrapped_project_dek": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.ProjectResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.PublicKeyResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "public_key": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.RecoverWithKitRequest": {
            "type": "object",
            "properties": {
                "new_auth_key_hash": {
                    "type": "string"
                },
                "new_recovery_wrapped_dek": {
                    "type": "string"
                },
                "new_salt": {
                    "type": "string"
                },
                "new_vault_key_type": {
                    "type": "string"
                },
                "new_wrapped_dek": {
                    "type": "string"
                },
                "new_wrapped_private_key": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.RecoveryKitResponse": {
            "type": "object",
            "properties": {
                "recovery_wrapped_dek": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.RecoveryRequestStatusResponse": {
            "type": "object",
            "properties": {
                "eligible_at": {
                    "type": "string"
                },
                "has_payload": {
                    "type": "boolean"
                },
                "request_id": {
                    "type": "string"
                },
                "requested_at": {
                    "type": "string"
                },
                "status": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.RecoveryStatusResponse": {
            "type": "object",
            "properties": {
                "contact_email": {
                    "type": "string"
                },
                "has_contact": {
                    "type": "boolean"
                },
                "has_kit": {
                    "type": "boolean"
                },
                "recovery_disabled": {
                    "type": "boolean"
                }
            }
        },
        "api_internal_handler.RollbackRequest": {
            "type": "object",
            "properties": {
                "version": {
                    "type": "integer"
                }
            }
        },
        "api_internal_handler.SecretListItem": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name_hash": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "api_internal_handler.SecretResponse": {
            "type": "object",
            "properties": {
                "ciphertext": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "environment": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name_hash": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "api_internal_handler.SetTrustedContactRequest": {
            "type": "object",
            "properties": {
                "contact_email": {
                    "type": "string"
                },
                "trusted_wrapped_dek": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.SetupVaultRequest": {
            "type": "object",
            "properties": {
                "auth_key_hash": {
                    "description": "base64",
                    "type": "string"
                },
                "public_key": {
                    "description": "base64",
                    "type": "string"
                },
                "recovery_disabled": {
                    "description": "enterprise opt-in to disable recovery",
                    "type": "boolean"
                },
                "recovery_wrapped_dek": {
                    "description": "base64, optional — DEK wrapped with recovery key",
                    "type": "string"
                },
                "salt": {
                    "description": "base64",
                    "type": "string"
                },
                "vault_key_type": {
                    "description": "\"pin\" or \"passphrase\"",
                    "type": "string"
                },
                "wrapped_dek": {
                    "description": "base64",
                    "type": "string"
                },
                "wrapped_private_key": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.SetupVaultResponse": {
            "type": "object",
            "properties": {
                "user_id": {
                    "type": "string"
                },
                "vault_setup_complete": {
                    "type": "boolean"
                }
            }
        },
        "api_internal_handler.TokenListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "environment": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "revoked_at": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.UnlockRequest": {
            "type": "object",
            "properties": {
                "auth_key_hash": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.UnlockResponse": {
            "type": "object",
            "properties": {
                "public_key": {
                    "description": "base64",
                    "type": "string"
                },
                "wrapped_dek": {
                    "description": "base64",
                    "type": "string"
                },
                "wrapped_private_key": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.UpdateSecretRequest": {
            "type": "object",
            "properties": {
                "ciphertext": {
                    "description": "base64",
                    "type": "string"
                },
                "nonce": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.VersionItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "api_internal_handler.VersionsResponse": {
            "type": "object",
            "properties": {
                "current_version": {
                    "type": "integer"
                },
                "versions": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_handler.VersionItem"
                    }
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Service token: \"Bearer ze_...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "SessionAuth": {
            "type": "apiKey",
            "name": "session_id",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "api.zenv.sh",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "zEnv API",
	Description:      "Zero-knowledge secret manager API. Stores and retrieves ciphertext. Never decrypts.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
