// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/auth/login": {
            "post": {
                "description": "Create session by email. Development only — replaced by OAuth in production.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Dev login (temporary)",
                "parameters": [
                    {
                        "description": "Email to login",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.DevLoginRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.DevLoginResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/logout": {
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Destroy session and clear cookie.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Logout",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "object",
                            "additionalProperties": {
                                "type": "string"
                            }
                        }
                    }
                }
            }
        },
        "/auth/signup": {
            "post": {
                "description": "Register with client-generated crypto material. Server stores ciphertext only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Create account",
                "parameters": [
                    {
                        "description": "Crypto material from client",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SignupRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SignupResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/auth/unlock": {
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Verify Auth Key hash (Vault Key proof). Returns wrapped DEK + keypair on success.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "auth"
                ],
                "summary": "Unlock vault",
                "parameters": [
                    {
                        "description": "Auth Key hash (base64)",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.UnlockRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.UnlockResponse"
                        }
                    },
                    "403": {
                        "description": "Wrong Vault Key",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "List all projects in an organization.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "List projects",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Organization ID",
                        "name": "organization_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ListProjectsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Create a project with client-generated crypto material. Project Vault Key shown once at creation, never stored on server.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Create project",
                "parameters": [
                    {
                        "description": "Project config + crypto material",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CreateProjectRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ProjectResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/projects/{projectID}": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Get a single project by ID.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get project",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ProjectResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sdk/projects/{projectID}/crypto": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Returns project salt and wrapped Project DEK. SDK uses this to derive Project KEK and unwrap DEK.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "projects"
                ],
                "summary": "Get project crypto",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project UUID",
                        "name": "projectID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ProjectCryptoResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sdk/secrets": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "List secret metadata (name hash, version, updated_at). Never returns ciphertext.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "List secrets",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ListSecretsResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Store an encrypted vault item. Server stores opaque ciphertext only.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Create secret",
                "parameters": [
                    {
                        "description": "Encrypted secret",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CreateSecretRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    },
                    "409": {
                        "description": "Conflict",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/sdk/secrets/bulk": {
            "post": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Fetch multiple secrets by name hashes. Used by SDK for schema manifest loading.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Bulk fetch secrets",
                "parameters": [
                    {
                        "description": "Name hashes to fetch",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.BulkFetchRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/api_internal_handler.SecretResponse"
                            }
                        }
                    }
                }
            }
        },
        "/sdk/secrets/{nameHash}": {
            "get": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Retrieve a single encrypted secret by name hash.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Get secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash (base64)",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment (development/staging/production)",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Update ciphertext and nonce. Version auto-incremented.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "secrets"
                ],
                "summary": "Update secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    },
                    {
                        "description": "New ciphertext",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.UpdateSecretRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.SecretResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "BearerAuth": []
                    }
                ],
                "description": "Remove a secret from the vault.",
                "tags": [
                    "secrets"
                ],
                "summary": "Delete secret",
                "parameters": [
                    {
                        "type": "string",
                        "description": "HMAC-SHA256 name hash",
                        "name": "nameHash",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Environment",
                        "name": "environment",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tokens": {
            "get": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "List all tokens for a project. Never exposes token hash or plaintext.",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "List service tokens",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Project ID",
                        "name": "project_id",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ListTokensResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Generate a scoped service token. Plaintext shown once, SHA-256 hashed before storage.",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "tokens"
                ],
                "summary": "Create service token",
                "parameters": [
                    {
                        "description": "Token config",
                        "name": "body",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CreateTokenRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.CreateTokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tokens/{tokenID}": {
            "delete": {
                "security": [
                    {
                        "SessionAuth": []
                    }
                ],
                "description": "Marks a service token as revoked. Immediate effect.",
                "tags": [
                    "tokens"
                ],
                "summary": "Revoke service token",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token UUID",
                        "name": "tokenID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK"
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/api_internal_handler.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "api_internal_handler.BulkFetchRequest": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "name_hashes": {
                    "description": "base64-encoded HMAC hashes",
                    "type": "array",
                    "items": {
                        "type": "string"
                    }
                },
                "project_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.CreateProjectRequest": {
            "type": "object",
            "properties": {
                "name": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "string"
                },
                "project_salt": {
                    "description": "base64 — generated client-side",
                    "type": "string"
                },
                "wrapped_project_dek": {
                    "description": "base64 — Project DEK wrapped with Project KEK",
                    "type": "string"
                },
                "wrapped_project_vault_key": {
                    "description": "base64 — Project Vault Key wrapped with user's public key",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.CreateSecretRequest": {
            "type": "object",
            "properties": {
                "ciphertext": {
                    "description": "base64 AES-256-GCM encrypted item JSON",
                    "type": "string"
                },
                "environment": {
                    "type": "string"
                },
                "name_hash": {
                    "description": "base64 HMAC-SHA256 of secret name",
                    "type": "string"
                },
                "nonce": {
                    "description": "base64 96-bit nonce",
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.CreateTokenRequest": {
            "type": "object",
            "properties": {
                "environment": {
                    "description": "development | staging | production",
                    "type": "string"
                },
                "expires_at": {
                    "description": "optional RFC3339",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permission": {
                    "description": "read | read_write",
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.CreateTokenResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "environment": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "token": {
                    "description": "shown exactly once — never stored",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.DevLoginRequest": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.DevLoginResponse": {
            "type": "object",
            "properties": {
                "salt": {
                    "description": "base64 — client needs this to re-derive KEK",
                    "type": "string"
                },
                "session_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                },
                "vault_key_type": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.ListProjectsResponse": {
            "type": "object",
            "properties": {
                "projects": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_handler.ProjectResponse"
                    }
                }
            }
        },
        "api_internal_handler.ListSecretsResponse": {
            "type": "object",
            "properties": {
                "secrets": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_handler.SecretListItem"
                    }
                }
            }
        },
        "api_internal_handler.ListTokensResponse": {
            "type": "object",
            "properties": {
                "tokens": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/api_internal_handler.TokenListItem"
                    }
                }
            }
        },
        "api_internal_handler.ProjectCryptoResponse": {
            "type": "object",
            "properties": {
                "project_salt": {
                    "description": "base64",
                    "type": "string"
                },
                "wrapped_project_dek": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.ProjectResponse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organization_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.SecretListItem": {
            "type": "object",
            "properties": {
                "environment": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name_hash": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "api_internal_handler.SecretResponse": {
            "type": "object",
            "properties": {
                "ciphertext": {
                    "type": "string"
                },
                "created_at": {
                    "type": "string"
                },
                "environment": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name_hash": {
                    "type": "string"
                },
                "nonce": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                },
                "version": {
                    "type": "integer"
                }
            }
        },
        "api_internal_handler.SignupRequest": {
            "type": "object",
            "properties": {
                "auth_key_hash": {
                    "description": "base64",
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "public_key": {
                    "description": "base64",
                    "type": "string"
                },
                "salt": {
                    "description": "base64",
                    "type": "string"
                },
                "vault_key_type": {
                    "description": "\"pin\" or \"passphrase\"",
                    "type": "string"
                },
                "wrapped_dek": {
                    "description": "base64",
                    "type": "string"
                },
                "wrapped_private_key": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.SignupResponse": {
            "type": "object",
            "properties": {
                "session_id": {
                    "type": "string"
                },
                "user_id": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.TokenListItem": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "environment": {
                    "type": "string"
                },
                "expires_at": {
                    "type": "string"
                },
                "id": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "permission": {
                    "type": "string"
                },
                "project_id": {
                    "type": "string"
                },
                "revoked_at": {
                    "type": "string"
                }
            }
        },
        "api_internal_handler.UnlockRequest": {
            "type": "object",
            "properties": {
                "auth_key_hash": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.UnlockResponse": {
            "type": "object",
            "properties": {
                "public_key": {
                    "description": "base64",
                    "type": "string"
                },
                "wrapped_dek": {
                    "description": "base64",
                    "type": "string"
                },
                "wrapped_private_key": {
                    "description": "base64",
                    "type": "string"
                }
            }
        },
        "api_internal_handler.UpdateSecretRequest": {
            "type": "object",
            "properties": {
                "ciphertext": {
                    "description": "base64",
                    "type": "string"
                },
                "nonce": {
                    "description": "base64",
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "BearerAuth": {
            "description": "Service token: \"Bearer svc_...\"",
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        },
        "SessionAuth": {
            "type": "apiKey",
            "name": "session_id",
            "in": "cookie"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "0.1.0",
	Host:             "api.zenv.sh",
	BasePath:         "/v1",
	Schemes:          []string{},
	Title:            "zEnv API",
	Description:      "Zero-knowledge secret manager API. Stores and retrieves ciphertext. Never decrypts.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
