/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Dev login (temporary)
         * @description Create session by email. Development only — replaced by OAuth in production.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Email to login */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.DevLoginRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.DevLoginResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout
         * @description Destroy session and clear cookie.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get auth state
         * @description Returns identity, vault setup status, and vault lock state.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.MeResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/setup-vault": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Setup vault
         * @description Store client-generated crypto material and link to authenticated identity.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Crypto material from client */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.SetupVaultRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.SetupVaultResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Create account
         * @description Register with client-generated crypto material. Server stores ciphertext only.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Crypto material from client */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.SignupRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.SignupResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/unlock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Unlock vault
         * @description Verify Auth Key hash (Vault Key proof). Returns wrapped DEK + keypair on success.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Auth Key hash (base64) */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.UnlockRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.UnlockResponse"];
                    };
                };
                /** @description Wrong Vault Key */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organizations
         * @description List all organizations the current user is a member of.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ListOrgsResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create organization
         * @description Create an organization. The creating user becomes the owner and is added as an admin member.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Organization name */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.CreateOrgRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.OrgResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get organization
         * @description Get a single organization by ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Organization UUID */
                    orgID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.OrgResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgID}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List organization members
         * @description List all members of an organization with their roles.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Organization UUID */
                    orgID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ListMembersResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Add organization member
         * @description Add a user to an organization with a specified role.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Organization UUID */
                    orgID: string;
                };
                cookie?: never;
            };
            /** @description User and role */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.AddMemberRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.MemberResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/orgs/{orgID}/members/{memberID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Remove organization member
         * @description Remove a member from an organization.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Organization UUID */
                    orgID: string;
                    /** @description Member UUID */
                    memberID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            [key: string]: string;
                        };
                    };
                };
                /** @description Forbidden */
                403: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List projects
         * @description List all projects in an organization.
         */
        get: {
            parameters: {
                query: {
                    /** @description Organization ID */
                    organization_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ListProjectsResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create project
         * @description Create a project with client-generated crypto material. Project Vault Key shown once at creation, never stored on server.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Project config + crypto material */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.CreateProjectRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ProjectResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/projects/{projectID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project
         * @description Get a single project by ID.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project UUID */
                    projectID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ProjectResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sdk/projects/{projectID}/crypto": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get project crypto
         * @description Returns project salt and wrapped Project DEK. SDK uses this to derive Project KEK and unwrap DEK.
         */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Project UUID */
                    projectID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ProjectCryptoResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sdk/secrets": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List secrets
         * @description List secret metadata (name hash, version, updated_at). Never returns ciphertext.
         */
        get: {
            parameters: {
                query: {
                    /** @description Project ID */
                    project_id: string;
                    /** @description Environment */
                    environment: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ListSecretsResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create secret
         * @description Store an encrypted vault item. Server stores opaque ciphertext only.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Encrypted secret */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.CreateSecretRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.SecretResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
                /** @description Conflict */
                409: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sdk/secrets/bulk": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Bulk fetch secrets
         * @description Fetch multiple secrets by name hashes. Used by SDK for schema manifest loading.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Name hashes to fetch */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.BulkFetchRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.SecretResponse"][];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sdk/secrets/{nameHash}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get secret
         * @description Retrieve a single encrypted secret by name hash.
         */
        get: {
            parameters: {
                query: {
                    /** @description Project ID */
                    project_id: string;
                    /** @description Environment (development/staging/production) */
                    environment: string;
                };
                header?: never;
                path: {
                    /** @description HMAC-SHA256 name hash (base64) */
                    nameHash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.SecretResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        /**
         * Update secret
         * @description Update ciphertext and nonce. Version auto-incremented.
         */
        put: {
            parameters: {
                query: {
                    /** @description Project ID */
                    project_id: string;
                    /** @description Environment */
                    environment: string;
                };
                header?: never;
                path: {
                    /** @description HMAC-SHA256 name hash */
                    nameHash: string;
                };
                cookie?: never;
            };
            /** @description New ciphertext */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.UpdateSecretRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.SecretResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        post?: never;
        /**
         * Delete secret
         * @description Remove a secret from the vault.
         */
        delete: {
            parameters: {
                query: {
                    /** @description Project ID */
                    project_id: string;
                    /** @description Environment */
                    environment: string;
                };
                header?: never;
                path: {
                    /** @description HMAC-SHA256 name hash */
                    nameHash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sdk/secrets/{nameHash}/rollback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Rollback secret
         * @description Revert a secret to a previous version. The current version is archived first.
         */
        post: {
            parameters: {
                query: {
                    /** @description Project ID */
                    project_id: string;
                    /** @description Environment */
                    environment: string;
                };
                header?: never;
                path: {
                    /** @description HMAC-SHA256 name hash */
                    nameHash: string;
                };
                cookie?: never;
            };
            /** @description Target version */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.RollbackRequest"];
                };
            };
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.SecretResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/sdk/secrets/{nameHash}/versions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List secret versions
         * @description Show version history for a secret. Returns version numbers and timestamps.
         */
        get: {
            parameters: {
                query: {
                    /** @description Project ID */
                    project_id: string;
                    /** @description Environment */
                    environment: string;
                };
                header?: never;
                path: {
                    /** @description HMAC-SHA256 name hash */
                    nameHash: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.VersionsResponse"];
                    };
                };
                /** @description Not Found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List service tokens
         * @description List all tokens for a project. Never exposes token hash or plaintext.
         */
        get: {
            parameters: {
                query: {
                    /** @description Project ID */
                    project_id: string;
                };
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ListTokensResponse"];
                    };
                };
            };
        };
        put?: never;
        /**
         * Create service token
         * @description Generate a scoped service token. Plaintext shown once, SHA-256 hashed before storage.
         */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            /** @description Token config */
            requestBody: {
                content: {
                    "application/json": components["schemas"]["api_internal_handler.CreateTokenRequest"];
                };
            };
            responses: {
                /** @description Created */
                201: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.CreateTokenResponse"];
                    };
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/tokens/{tokenID}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /**
         * Revoke service token
         * @description Marks a service token as revoked. Immediate effect.
         */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description Token UUID */
                    tokenID: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "*/*": components["schemas"]["api_internal_handler.ErrorResponse"];
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        "api_internal_handler.AddMemberRequest": {
            /** @description admin, senior_dev, dev, contractor, ci_bot */
            role?: string;
            user_id?: string;
        };
        "api_internal_handler.BulkFetchRequest": {
            environment?: string;
            /** @description base64-encoded HMAC hashes */
            name_hashes?: string[];
            project_id?: string;
        };
        "api_internal_handler.CreateOrgRequest": {
            name?: string;
        };
        "api_internal_handler.CreateProjectRequest": {
            name?: string;
            organization_id?: string;
            /** @description base64 — generated client-side */
            project_salt?: string;
            /** @description base64 — Project DEK wrapped with Project KEK */
            wrapped_project_dek?: string;
            /** @description base64 — Project Vault Key wrapped with user's public key */
            wrapped_project_vault_key?: string;
        };
        "api_internal_handler.CreateSecretRequest": {
            /** @description base64 AES-256-GCM encrypted item JSON */
            ciphertext?: string;
            environment?: string;
            /** @description base64 HMAC-SHA256 of secret name */
            name_hash?: string;
            /** @description base64 96-bit nonce */
            nonce?: string;
            project_id?: string;
        };
        "api_internal_handler.CreateTokenRequest": {
            /** @description development | staging | production */
            environment?: string;
            /** @description optional RFC3339 */
            expires_at?: string;
            name?: string;
            /** @description read | read_write */
            permission?: string;
            project_id?: string;
        };
        "api_internal_handler.CreateTokenResponse": {
            created_at?: string;
            environment?: string;
            expires_at?: string;
            id?: string;
            name?: string;
            permission?: string;
            project_id?: string;
            /** @description shown exactly once — never stored */
            token?: string;
        };
        "api_internal_handler.DevLoginRequest": {
            email?: string;
        };
        "api_internal_handler.DevLoginResponse": {
            /** @description base64 — client needs this to re-derive KEK */
            salt?: string;
            session_id?: string;
            user_id?: string;
            vault_key_type?: string;
        };
        "api_internal_handler.ErrorResponse": {
            error?: string;
        };
        "api_internal_handler.ListMembersResponse": {
            members?: components["schemas"]["api_internal_handler.MemberResponse"][];
        };
        "api_internal_handler.ListOrgsResponse": {
            organizations?: components["schemas"]["api_internal_handler.OrgResponse"][];
        };
        "api_internal_handler.ListProjectsResponse": {
            projects?: components["schemas"]["api_internal_handler.ProjectResponse"][];
        };
        "api_internal_handler.ListSecretsResponse": {
            secrets?: components["schemas"]["api_internal_handler.SecretListItem"][];
        };
        "api_internal_handler.ListTokensResponse": {
            tokens?: components["schemas"]["api_internal_handler.TokenListItem"][];
        };
        "api_internal_handler.MeResponse": {
            email?: string;
            /** @description base64 */
            salt?: string;
            vault_key_type?: string;
            vault_setup_complete?: boolean;
            vault_unlocked?: boolean;
        };
        "api_internal_handler.MemberResponse": {
            email?: string;
            id?: string;
            joined_at?: string;
            role?: string;
            user_id?: string;
        };
        "api_internal_handler.OrgResponse": {
            created_at?: string;
            id?: string;
            name?: string;
            owner_id?: string;
        };
        "api_internal_handler.ProjectCryptoResponse": {
            /** @description base64 */
            project_salt?: string;
            /** @description base64 */
            wrapped_project_dek?: string;
        };
        "api_internal_handler.ProjectResponse": {
            created_at?: string;
            id?: string;
            name?: string;
            organization_id?: string;
        };
        "api_internal_handler.RollbackRequest": {
            version?: number;
        };
        "api_internal_handler.SecretListItem": {
            environment?: string;
            id?: string;
            name_hash?: string;
            updated_at?: string;
            version?: number;
        };
        "api_internal_handler.SecretResponse": {
            ciphertext?: string;
            created_at?: string;
            environment?: string;
            id?: string;
            name_hash?: string;
            nonce?: string;
            project_id?: string;
            updated_at?: string;
            version?: number;
        };
        "api_internal_handler.SetupVaultRequest": {
            /** @description base64 */
            auth_key_hash?: string;
            /** @description base64 */
            public_key?: string;
            /** @description base64 */
            salt?: string;
            /** @description "pin" or "passphrase" */
            vault_key_type?: string;
            /** @description base64 */
            wrapped_dek?: string;
            /** @description base64 */
            wrapped_private_key?: string;
        };
        "api_internal_handler.SetupVaultResponse": {
            user_id?: string;
            vault_setup_complete?: boolean;
        };
        "api_internal_handler.SignupRequest": {
            /** @description base64 */
            auth_key_hash?: string;
            email?: string;
            /** @description base64 */
            public_key?: string;
            /** @description base64 */
            salt?: string;
            /** @description "pin" or "passphrase" */
            vault_key_type?: string;
            /** @description base64 */
            wrapped_dek?: string;
            /** @description base64 */
            wrapped_private_key?: string;
        };
        "api_internal_handler.SignupResponse": {
            session_id?: string;
            user_id?: string;
        };
        "api_internal_handler.TokenListItem": {
            created_at?: string;
            environment?: string;
            expires_at?: string;
            id?: string;
            name?: string;
            permission?: string;
            project_id?: string;
            revoked_at?: string;
        };
        "api_internal_handler.UnlockRequest": {
            /** @description base64 */
            auth_key_hash?: string;
        };
        "api_internal_handler.UnlockResponse": {
            /** @description base64 */
            public_key?: string;
            /** @description base64 */
            wrapped_dek?: string;
            /** @description base64 */
            wrapped_private_key?: string;
        };
        "api_internal_handler.UpdateSecretRequest": {
            /** @description base64 */
            ciphertext?: string;
            /** @description base64 */
            nonce?: string;
        };
        "api_internal_handler.VersionItem": {
            created_at?: string;
            version?: number;
        };
        "api_internal_handler.VersionsResponse": {
            current_version?: number;
            versions?: components["schemas"]["api_internal_handler.VersionItem"][];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
