/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ComponentsRouteImport } from './routes/components'
import { Route as AuthedRouteRouteImport } from './routes/_authed/route'
import { Route as RecoverIndexRouteImport } from './routes/recover/index'
import { Route as RecoverTrustedContactRouteImport } from './routes/recover/trusted-contact'
import { Route as RecoverKitRouteImport } from './routes/recover/kit'
import { Route as JoinTokenRouteImport } from './routes/join.$token'
import { Route as AuthedVaultSetupRouteImport } from './routes/_authed/vault-setup'
import { Route as AuthedUnlockRouteImport } from './routes/_authed/unlock'
import { Route as AuthedUnlockedRouteRouteImport } from './routes/_authed/_unlocked/route'
import { Route as AuthedUnlockedIndexRouteImport } from './routes/_authed/_unlocked/index'
import { Route as AuthedUnlockedSettingsRouteImport } from './routes/_authed/_unlocked/settings'
import { Route as AuthedUnlockedOnboardingRouteImport } from './routes/_authed/_unlocked/onboarding'
import { Route as AuthedUnlockedOrgsOrgIdRouteRouteImport } from './routes/_authed/_unlocked/orgs/$orgId/route'
import { Route as AuthedUnlockedOrgsOrgIdIndexRouteImport } from './routes/_authed/_unlocked/orgs/$orgId/index'
import { Route as AuthedUnlockedOrgsOrgIdSettingsRouteImport } from './routes/_authed/_unlocked/orgs/$orgId/settings'
import { Route as AuthedUnlockedOrgsOrgIdMembersRouteImport } from './routes/_authed/_unlocked/orgs/$orgId/members'
import { Route as AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteImport } from './routes/_authed/_unlocked/orgs/$orgId/projects/$projectId/route'
import { Route as AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRouteImport } from './routes/_authed/_unlocked/orgs/$orgId/projects/$projectId/index'
import { Route as AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRouteImport } from './routes/_authed/_unlocked/orgs/$orgId/projects/$projectId/tokens'
import { Route as AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRouteImport } from './routes/_authed/_unlocked/orgs/$orgId/projects/$projectId/settings'
import { Route as AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRouteImport } from './routes/_authed/_unlocked/orgs/$orgId/projects/$projectId/secrets'
import { Route as AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRouteImport } from './routes/_authed/_unlocked/orgs/$orgId/projects/$projectId/audit'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ComponentsRoute = ComponentsRouteImport.update({
  id: '/components',
  path: '/components',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedRouteRoute = AuthedRouteRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverIndexRoute = RecoverIndexRouteImport.update({
  id: '/recover/',
  path: '/recover/',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverTrustedContactRoute = RecoverTrustedContactRouteImport.update({
  id: '/recover/trusted-contact',
  path: '/recover/trusted-contact',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverKitRoute = RecoverKitRouteImport.update({
  id: '/recover/kit',
  path: '/recover/kit',
  getParentRoute: () => rootRouteImport,
} as any)
const JoinTokenRoute = JoinTokenRouteImport.update({
  id: '/join/$token',
  path: '/join/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedVaultSetupRoute = AuthedVaultSetupRouteImport.update({
  id: '/vault-setup',
  path: '/vault-setup',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedUnlockRoute = AuthedUnlockRouteImport.update({
  id: '/unlock',
  path: '/unlock',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedUnlockedRouteRoute = AuthedUnlockedRouteRouteImport.update({
  id: '/_unlocked',
  getParentRoute: () => AuthedRouteRoute,
} as any)
const AuthedUnlockedIndexRoute = AuthedUnlockedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedUnlockedRouteRoute,
} as any)
const AuthedUnlockedSettingsRoute = AuthedUnlockedSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AuthedUnlockedRouteRoute,
} as any)
const AuthedUnlockedOnboardingRoute =
  AuthedUnlockedOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthedUnlockedRouteRoute,
  } as any)
const AuthedUnlockedOrgsOrgIdRouteRoute =
  AuthedUnlockedOrgsOrgIdRouteRouteImport.update({
    id: '/orgs/$orgId',
    path: '/orgs/$orgId',
    getParentRoute: () => AuthedUnlockedRouteRoute,
  } as any)
const AuthedUnlockedOrgsOrgIdIndexRoute =
  AuthedUnlockedOrgsOrgIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedUnlockedOrgsOrgIdRouteRoute,
  } as any)
const AuthedUnlockedOrgsOrgIdSettingsRoute =
  AuthedUnlockedOrgsOrgIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedUnlockedOrgsOrgIdRouteRoute,
  } as any)
const AuthedUnlockedOrgsOrgIdMembersRoute =
  AuthedUnlockedOrgsOrgIdMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthedUnlockedOrgsOrgIdRouteRoute,
  } as any)
const AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute =
  AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteImport.update({
    id: '/projects/$projectId',
    path: '/projects/$projectId',
    getParentRoute: () => AuthedUnlockedOrgsOrgIdRouteRoute,
  } as any)
const AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRoute =
  AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute,
  } as any)
const AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRoute =
  AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRouteImport.update({
    id: '/tokens',
    path: '/tokens',
    getParentRoute: () => AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute,
  } as any)
const AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRoute =
  AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute,
  } as any)
const AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRoute =
  AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRouteImport.update({
    id: '/secrets',
    path: '/secrets',
    getParentRoute: () => AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute,
  } as any)
const AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRoute =
  AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedUnlockedIndexRoute
  '/components': typeof ComponentsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unlock': typeof AuthedUnlockRoute
  '/vault-setup': typeof AuthedVaultSetupRoute
  '/join/$token': typeof JoinTokenRoute
  '/recover/kit': typeof RecoverKitRoute
  '/recover/trusted-contact': typeof RecoverTrustedContactRoute
  '/recover/': typeof RecoverIndexRoute
  '/onboarding': typeof AuthedUnlockedOnboardingRoute
  '/settings': typeof AuthedUnlockedSettingsRoute
  '/orgs/$orgId': typeof AuthedUnlockedOrgsOrgIdRouteRouteWithChildren
  '/orgs/$orgId/members': typeof AuthedUnlockedOrgsOrgIdMembersRoute
  '/orgs/$orgId/settings': typeof AuthedUnlockedOrgsOrgIdSettingsRoute
  '/orgs/$orgId/': typeof AuthedUnlockedOrgsOrgIdIndexRoute
  '/orgs/$orgId/projects/$projectId': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteWithChildren
  '/orgs/$orgId/projects/$projectId/audit': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRoute
  '/orgs/$orgId/projects/$projectId/secrets': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRoute
  '/orgs/$orgId/projects/$projectId/settings': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRoute
  '/orgs/$orgId/projects/$projectId/tokens': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRoute
  '/orgs/$orgId/projects/$projectId/': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof AuthedUnlockedIndexRoute
  '/components': typeof ComponentsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/unlock': typeof AuthedUnlockRoute
  '/vault-setup': typeof AuthedVaultSetupRoute
  '/join/$token': typeof JoinTokenRoute
  '/recover/kit': typeof RecoverKitRoute
  '/recover/trusted-contact': typeof RecoverTrustedContactRoute
  '/recover': typeof RecoverIndexRoute
  '/onboarding': typeof AuthedUnlockedOnboardingRoute
  '/settings': typeof AuthedUnlockedSettingsRoute
  '/orgs/$orgId/members': typeof AuthedUnlockedOrgsOrgIdMembersRoute
  '/orgs/$orgId/settings': typeof AuthedUnlockedOrgsOrgIdSettingsRoute
  '/orgs/$orgId': typeof AuthedUnlockedOrgsOrgIdIndexRoute
  '/orgs/$orgId/projects/$projectId/audit': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRoute
  '/orgs/$orgId/projects/$projectId/secrets': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRoute
  '/orgs/$orgId/projects/$projectId/settings': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRoute
  '/orgs/$orgId/projects/$projectId/tokens': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRoute
  '/orgs/$orgId/projects/$projectId': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteRouteWithChildren
  '/components': typeof ComponentsRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_authed/_unlocked': typeof AuthedUnlockedRouteRouteWithChildren
  '/_authed/unlock': typeof AuthedUnlockRoute
  '/_authed/vault-setup': typeof AuthedVaultSetupRoute
  '/join/$token': typeof JoinTokenRoute
  '/recover/kit': typeof RecoverKitRoute
  '/recover/trusted-contact': typeof RecoverTrustedContactRoute
  '/recover/': typeof RecoverIndexRoute
  '/_authed/_unlocked/onboarding': typeof AuthedUnlockedOnboardingRoute
  '/_authed/_unlocked/settings': typeof AuthedUnlockedSettingsRoute
  '/_authed/_unlocked/': typeof AuthedUnlockedIndexRoute
  '/_authed/_unlocked/orgs/$orgId': typeof AuthedUnlockedOrgsOrgIdRouteRouteWithChildren
  '/_authed/_unlocked/orgs/$orgId/members': typeof AuthedUnlockedOrgsOrgIdMembersRoute
  '/_authed/_unlocked/orgs/$orgId/settings': typeof AuthedUnlockedOrgsOrgIdSettingsRoute
  '/_authed/_unlocked/orgs/$orgId/': typeof AuthedUnlockedOrgsOrgIdIndexRoute
  '/_authed/_unlocked/orgs/$orgId/projects/$projectId': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteWithChildren
  '/_authed/_unlocked/orgs/$orgId/projects/$projectId/audit': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRoute
  '/_authed/_unlocked/orgs/$orgId/projects/$projectId/secrets': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRoute
  '/_authed/_unlocked/orgs/$orgId/projects/$projectId/settings': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRoute
  '/_authed/_unlocked/orgs/$orgId/projects/$projectId/tokens': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRoute
  '/_authed/_unlocked/orgs/$orgId/projects/$projectId/': typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/components'
    | '/login'
    | '/signup'
    | '/unlock'
    | '/vault-setup'
    | '/join/$token'
    | '/recover/kit'
    | '/recover/trusted-contact'
    | '/recover/'
    | '/onboarding'
    | '/settings'
    | '/orgs/$orgId'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId/'
    | '/orgs/$orgId/projects/$projectId'
    | '/orgs/$orgId/projects/$projectId/audit'
    | '/orgs/$orgId/projects/$projectId/secrets'
    | '/orgs/$orgId/projects/$projectId/settings'
    | '/orgs/$orgId/projects/$projectId/tokens'
    | '/orgs/$orgId/projects/$projectId/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/components'
    | '/login'
    | '/signup'
    | '/unlock'
    | '/vault-setup'
    | '/join/$token'
    | '/recover/kit'
    | '/recover/trusted-contact'
    | '/recover'
    | '/onboarding'
    | '/settings'
    | '/orgs/$orgId/members'
    | '/orgs/$orgId/settings'
    | '/orgs/$orgId'
    | '/orgs/$orgId/projects/$projectId/audit'
    | '/orgs/$orgId/projects/$projectId/secrets'
    | '/orgs/$orgId/projects/$projectId/settings'
    | '/orgs/$orgId/projects/$projectId/tokens'
    | '/orgs/$orgId/projects/$projectId'
  id:
    | '__root__'
    | '/_authed'
    | '/components'
    | '/login'
    | '/signup'
    | '/_authed/_unlocked'
    | '/_authed/unlock'
    | '/_authed/vault-setup'
    | '/join/$token'
    | '/recover/kit'
    | '/recover/trusted-contact'
    | '/recover/'
    | '/_authed/_unlocked/onboarding'
    | '/_authed/_unlocked/settings'
    | '/_authed/_unlocked/'
    | '/_authed/_unlocked/orgs/$orgId'
    | '/_authed/_unlocked/orgs/$orgId/members'
    | '/_authed/_unlocked/orgs/$orgId/settings'
    | '/_authed/_unlocked/orgs/$orgId/'
    | '/_authed/_unlocked/orgs/$orgId/projects/$projectId'
    | '/_authed/_unlocked/orgs/$orgId/projects/$projectId/audit'
    | '/_authed/_unlocked/orgs/$orgId/projects/$projectId/secrets'
    | '/_authed/_unlocked/orgs/$orgId/projects/$projectId/settings'
    | '/_authed/_unlocked/orgs/$orgId/projects/$projectId/tokens'
    | '/_authed/_unlocked/orgs/$orgId/projects/$projectId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRouteRoute: typeof AuthedRouteRouteWithChildren
  ComponentsRoute: typeof ComponentsRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  JoinTokenRoute: typeof JoinTokenRoute
  RecoverKitRoute: typeof RecoverKitRoute
  RecoverTrustedContactRoute: typeof RecoverTrustedContactRoute
  RecoverIndexRoute: typeof RecoverIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/components': {
      id: '/components'
      path: '/components'
      fullPath: '/components'
      preLoaderRoute: typeof ComponentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/': {
      id: '/recover/'
      path: '/recover'
      fullPath: '/recover/'
      preLoaderRoute: typeof RecoverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/trusted-contact': {
      id: '/recover/trusted-contact'
      path: '/recover/trusted-contact'
      fullPath: '/recover/trusted-contact'
      preLoaderRoute: typeof RecoverTrustedContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover/kit': {
      id: '/recover/kit'
      path: '/recover/kit'
      fullPath: '/recover/kit'
      preLoaderRoute: typeof RecoverKitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/join/$token': {
      id: '/join/$token'
      path: '/join/$token'
      fullPath: '/join/$token'
      preLoaderRoute: typeof JoinTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/vault-setup': {
      id: '/_authed/vault-setup'
      path: '/vault-setup'
      fullPath: '/vault-setup'
      preLoaderRoute: typeof AuthedVaultSetupRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/unlock': {
      id: '/_authed/unlock'
      path: '/unlock'
      fullPath: '/unlock'
      preLoaderRoute: typeof AuthedUnlockRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_unlocked': {
      id: '/_authed/_unlocked'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedUnlockedRouteRouteImport
      parentRoute: typeof AuthedRouteRoute
    }
    '/_authed/_unlocked/': {
      id: '/_authed/_unlocked/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedUnlockedIndexRouteImport
      parentRoute: typeof AuthedUnlockedRouteRoute
    }
    '/_authed/_unlocked/settings': {
      id: '/_authed/_unlocked/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AuthedUnlockedSettingsRouteImport
      parentRoute: typeof AuthedUnlockedRouteRoute
    }
    '/_authed/_unlocked/onboarding': {
      id: '/_authed/_unlocked/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof AuthedUnlockedOnboardingRouteImport
      parentRoute: typeof AuthedUnlockedRouteRoute
    }
    '/_authed/_unlocked/orgs/$orgId': {
      id: '/_authed/_unlocked/orgs/$orgId'
      path: '/orgs/$orgId'
      fullPath: '/orgs/$orgId'
      preLoaderRoute: typeof AuthedUnlockedOrgsOrgIdRouteRouteImport
      parentRoute: typeof AuthedUnlockedRouteRoute
    }
    '/_authed/_unlocked/orgs/$orgId/': {
      id: '/_authed/_unlocked/orgs/$orgId/'
      path: '/'
      fullPath: '/orgs/$orgId/'
      preLoaderRoute: typeof AuthedUnlockedOrgsOrgIdIndexRouteImport
      parentRoute: typeof AuthedUnlockedOrgsOrgIdRouteRoute
    }
    '/_authed/_unlocked/orgs/$orgId/settings': {
      id: '/_authed/_unlocked/orgs/$orgId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/settings'
      preLoaderRoute: typeof AuthedUnlockedOrgsOrgIdSettingsRouteImport
      parentRoute: typeof AuthedUnlockedOrgsOrgIdRouteRoute
    }
    '/_authed/_unlocked/orgs/$orgId/members': {
      id: '/_authed/_unlocked/orgs/$orgId/members'
      path: '/members'
      fullPath: '/orgs/$orgId/members'
      preLoaderRoute: typeof AuthedUnlockedOrgsOrgIdMembersRouteImport
      parentRoute: typeof AuthedUnlockedOrgsOrgIdRouteRoute
    }
    '/_authed/_unlocked/orgs/$orgId/projects/$projectId': {
      id: '/_authed/_unlocked/orgs/$orgId/projects/$projectId'
      path: '/projects/$projectId'
      fullPath: '/orgs/$orgId/projects/$projectId'
      preLoaderRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteImport
      parentRoute: typeof AuthedUnlockedOrgsOrgIdRouteRoute
    }
    '/_authed/_unlocked/orgs/$orgId/projects/$projectId/': {
      id: '/_authed/_unlocked/orgs/$orgId/projects/$projectId/'
      path: '/'
      fullPath: '/orgs/$orgId/projects/$projectId/'
      preLoaderRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRouteImport
      parentRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute
    }
    '/_authed/_unlocked/orgs/$orgId/projects/$projectId/tokens': {
      id: '/_authed/_unlocked/orgs/$orgId/projects/$projectId/tokens'
      path: '/tokens'
      fullPath: '/orgs/$orgId/projects/$projectId/tokens'
      preLoaderRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRouteImport
      parentRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute
    }
    '/_authed/_unlocked/orgs/$orgId/projects/$projectId/settings': {
      id: '/_authed/_unlocked/orgs/$orgId/projects/$projectId/settings'
      path: '/settings'
      fullPath: '/orgs/$orgId/projects/$projectId/settings'
      preLoaderRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRouteImport
      parentRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute
    }
    '/_authed/_unlocked/orgs/$orgId/projects/$projectId/secrets': {
      id: '/_authed/_unlocked/orgs/$orgId/projects/$projectId/secrets'
      path: '/secrets'
      fullPath: '/orgs/$orgId/projects/$projectId/secrets'
      preLoaderRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRouteImport
      parentRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute
    }
    '/_authed/_unlocked/orgs/$orgId/projects/$projectId/audit': {
      id: '/_authed/_unlocked/orgs/$orgId/projects/$projectId/audit'
      path: '/audit'
      fullPath: '/orgs/$orgId/projects/$projectId/audit'
      preLoaderRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRouteImport
      parentRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute
    }
  }
}

interface AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteChildren {
  AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRoute
  AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRoute
  AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRoute
  AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRoute
  AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRoute
}

const AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteChildren: AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteChildren =
  {
    AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRoute:
      AuthedUnlockedOrgsOrgIdProjectsProjectIdAuditRoute,
    AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRoute:
      AuthedUnlockedOrgsOrgIdProjectsProjectIdSecretsRoute,
    AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRoute:
      AuthedUnlockedOrgsOrgIdProjectsProjectIdSettingsRoute,
    AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRoute:
      AuthedUnlockedOrgsOrgIdProjectsProjectIdTokensRoute,
    AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRoute:
      AuthedUnlockedOrgsOrgIdProjectsProjectIdIndexRoute,
  }

const AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteWithChildren =
  AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute._addFileChildren(
    AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteChildren,
  )

interface AuthedUnlockedOrgsOrgIdRouteRouteChildren {
  AuthedUnlockedOrgsOrgIdMembersRoute: typeof AuthedUnlockedOrgsOrgIdMembersRoute
  AuthedUnlockedOrgsOrgIdSettingsRoute: typeof AuthedUnlockedOrgsOrgIdSettingsRoute
  AuthedUnlockedOrgsOrgIdIndexRoute: typeof AuthedUnlockedOrgsOrgIdIndexRoute
  AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute: typeof AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteWithChildren
}

const AuthedUnlockedOrgsOrgIdRouteRouteChildren: AuthedUnlockedOrgsOrgIdRouteRouteChildren =
  {
    AuthedUnlockedOrgsOrgIdMembersRoute: AuthedUnlockedOrgsOrgIdMembersRoute,
    AuthedUnlockedOrgsOrgIdSettingsRoute: AuthedUnlockedOrgsOrgIdSettingsRoute,
    AuthedUnlockedOrgsOrgIdIndexRoute: AuthedUnlockedOrgsOrgIdIndexRoute,
    AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRoute:
      AuthedUnlockedOrgsOrgIdProjectsProjectIdRouteRouteWithChildren,
  }

const AuthedUnlockedOrgsOrgIdRouteRouteWithChildren =
  AuthedUnlockedOrgsOrgIdRouteRoute._addFileChildren(
    AuthedUnlockedOrgsOrgIdRouteRouteChildren,
  )

interface AuthedUnlockedRouteRouteChildren {
  AuthedUnlockedOnboardingRoute: typeof AuthedUnlockedOnboardingRoute
  AuthedUnlockedSettingsRoute: typeof AuthedUnlockedSettingsRoute
  AuthedUnlockedIndexRoute: typeof AuthedUnlockedIndexRoute
  AuthedUnlockedOrgsOrgIdRouteRoute: typeof AuthedUnlockedOrgsOrgIdRouteRouteWithChildren
}

const AuthedUnlockedRouteRouteChildren: AuthedUnlockedRouteRouteChildren = {
  AuthedUnlockedOnboardingRoute: AuthedUnlockedOnboardingRoute,
  AuthedUnlockedSettingsRoute: AuthedUnlockedSettingsRoute,
  AuthedUnlockedIndexRoute: AuthedUnlockedIndexRoute,
  AuthedUnlockedOrgsOrgIdRouteRoute:
    AuthedUnlockedOrgsOrgIdRouteRouteWithChildren,
}

const AuthedUnlockedRouteRouteWithChildren =
  AuthedUnlockedRouteRoute._addFileChildren(AuthedUnlockedRouteRouteChildren)

interface AuthedRouteRouteChildren {
  AuthedUnlockedRouteRoute: typeof AuthedUnlockedRouteRouteWithChildren
  AuthedUnlockRoute: typeof AuthedUnlockRoute
  AuthedVaultSetupRoute: typeof AuthedVaultSetupRoute
}

const AuthedRouteRouteChildren: AuthedRouteRouteChildren = {
  AuthedUnlockedRouteRoute: AuthedUnlockedRouteRouteWithChildren,
  AuthedUnlockRoute: AuthedUnlockRoute,
  AuthedVaultSetupRoute: AuthedVaultSetupRoute,
}

const AuthedRouteRouteWithChildren = AuthedRouteRoute._addFileChildren(
  AuthedRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthedRouteRoute: AuthedRouteRouteWithChildren,
  ComponentsRoute: ComponentsRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  JoinTokenRoute: JoinTokenRoute,
  RecoverKitRoute: RecoverKitRoute,
  RecoverTrustedContactRoute: RecoverTrustedContactRoute,
  RecoverIndexRoute: RecoverIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
