/**
 * Cross-language parity tests.
 *
 * Reads test vectors generated by Go Amnesia (tests/vectors.json)
 * and validates that TypeScript Amnesia produces byte-identical output.
 * If any vector fails, Go and TS have drifted — fix before merging.
 */
import { test, expect, describe } from "bun:test";
import vectors from "../../../tests/vectors.json";
import { deriveKeys } from "./derive.ts";
import { hashName, hashAuthKey } from "./hash.ts";

function hex(b: Uint8Array): string {
  return Array.from(b)
    .map((x) => x.toString(16).padStart(2, "0"))
    .join("");
}

function unhex(s: string): Uint8Array {
  const bytes = new Uint8Array(s.length / 2);
  for (let i = 0; i < s.length; i += 2) {
    bytes[i / 2] = parseInt(s.substring(i, i + 2), 16);
  }
  return bytes;
}

describe("cross-language parity: deriveKeys", () => {
  for (const v of vectors.deriveKeys) {
    test(`vaultKey="${v.vaultKey}" keyType=${v.keyType}`, async () => {
      const { kek, authKey } = await deriveKeys(
        v.vaultKey,
        unhex(v.salt),
        v.keyType as "pin" | "passphrase",
      );
      expect(hex(kek)).toBe(v.kek);
      expect(hex(authKey)).toBe(v.authKey);
    });
  }
});

describe("cross-language parity: symmetric", () => {
  for (const v of vectors.symmetric) {
    test(`encrypt with fixed nonce`, async () => {
      // We can't call encrypt() with a fixed nonce via the public API
      // (it always generates a random nonce). Instead, verify decrypt
      // of Go-produced ciphertext works correctly.
      const key = unhex(v.key);
      const nonce = unhex(v.nonce);
      const ciphertext = unhex(v.ciphertext);
      const expectedPlaintext = unhex(v.plaintext);

      const { decrypt } = await import("./symmetric.ts");
      const decrypted = await decrypt(ciphertext, nonce, key);
      expect(hex(decrypted)).toBe(v.plaintext);
      expect(decrypted).toEqual(expectedPlaintext);
    });
  }
});

describe("cross-language parity: hashName", () => {
  for (const v of vectors.hashName) {
    test(`name="${v.name}"`, async () => {
      const hash = await hashName(v.name, unhex(v.hmacKey));
      expect(hex(hash)).toBe(v.hash);
    });
  }
});

describe("cross-language parity: hashAuthKey", () => {
  for (const v of vectors.hashAuthKey) {
    test(`authKey=${v.authKey.slice(0, 16)}...`, async () => {
      const hash = await hashAuthKey(unhex(v.authKey));
      expect(hex(hash)).toBe(v.hash);
    });
  }
});
